FROM nginx:mainline-alpine
COPY nginx-common-proxy.conf /etc/nginx/nginx-common-proxy.conf
COPY nginx-reverse-proxy.conf /etc/nginx/nginx.conf
COPY nginx-reverse-proxy.crt /etc/nginx/nginx.crt
COPY nginx-reverse-proxy.key /etc/nginx/nginx.key
