FROM mcr.microsoft.com/dotnet/sdk:10.0-alpine AS simplymeet-api-builder
WORKDIR /source
COPY ./Scripts /source/Scripts
COPY ./SimplyMeetApi /source/SimplyMeetApi
COPY ./SimplyMeetShared /source/SimplyMeetShared
COPY ./Directory.Build.props /source
RUN apk add --no-cache --update bash
RUN ./Scripts/build-no-docker.sh release linux-musl-x64 api

FROM mcr.microsoft.com/dotnet/runtime-deps:10.0-alpine AS simplymeet-api
WORKDIR /app
COPY --from=simplymeet-api-builder /source/Build/SimplyMeetApi .
RUN apk add --no-cache --update sqlite
ENTRYPOINT [ "./SimplyMeetApi" ]
