version: "3.9"
services:
    hiki-wasm:
        build: wasm
        ports:
            - "5001:5001"
        volumes:
            - hiki-wasm-app:/etc/nginx/html:ro
    hiki-webapi:
        build: webapi
        environment:
            - ASPNETCORE_ENVIRONMENT=Production
        ports:
            - "5002:5002"
        volumes:
            - hiki-webapi-app:/app:ro
            - hiki-webapi-data:/app/App_Data

volumes:
    hiki-wasm-app:
        external: false
    hiki-webapi-app:
        external: false
    hiki-webapi-data:
        external: false