services:
  wasm:
    hostname: wasm
    # image: ghcr.io/yalohi/SimplyMeet
    build: SimplyMeetWasm
    ports:
      - 5001:5001/tcp
  webapi:
    hostname: webapi
    # image: ghcr.io/yalohi/SimplyMeet
    build: SimplyMeetApi
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - 5002:5002/tcp
    volumes:
      - ./webapi/config/appsettings.Production.json:/app/appsettings.Production.json:ro
      - ./webapi/data/:/app/App_Data
