version: "3.4"
services:
    reverse-proxy:
        build: reverse-proxy
        container_name: ${COMPOSE_PROJECT_NAME}-reverse-proxy
        ports:
            - "443:443"
        depends_on:
            - wasm
            - webapi
    wasm:
        build: wasm
        container_name: ${COMPOSE_PROJECT_NAME}-wasm
        ports:
            - "5001:5001"
        volumes:
            - wasm-app:/etc/nginx/html:ro
    webapi:
        build: webapi
        container_name: ${COMPOSE_PROJECT_NAME}-webapi
        environment:
            - ASPNETCORE_ENVIRONMENT=Production
        ports:
            - "5002:5002"
        volumes:
            - webapi-app:/app:ro
            - webapi-data:/app/App_Data

volumes:
    wasm-app:
        name: ${COMPOSE_PROJECT_NAME}-wasm-app
        external: false
    webapi-app:
        name: ${COMPOSE_PROJECT_NAME}-webapi-app
        external: false
    webapi-data:
        name: ${COMPOSE_PROJECT_NAME}-webapi-data
        external: false