#!/bin/bash

SCRIPT_PATH=$(dirname $(realpath "$0"))

MY_DOCKER_PATH=Docker/
MY_BUILD_PATH=Build/
MY_BACKUPS_PATH=Backups/
MY_BACKUP_DAYS=7
MY_BACKUP_NAME=$(date +"%Y-%m-%d-%H-%M-%S").tar
MY_TEMP_BACKUP_PATH=/backup
MY_DATA_PATH=/app/App_Data

. ${SCRIPT_PATH}/../${MY_DOCKER_PATH}/.env

MY_CONTAINER_NAME_WEBAPI=${COMPOSE_PROJECT_NAME}-webapi
MY_VOLUME_NAME_WASM_APP=${COMPOSE_PROJECT_NAME}-wasm-app
MY_VOLUME_NAME_WEBAPI_APP=${COMPOSE_PROJECT_NAME}-webapi-app